import "./globals.css";
import { Inter } from "next/font/google";
import AuthProviders from "./authproviders";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Appointmentsystem",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProviders>
          <Navbar />
          <div className="md:!pl-16">{children}</div>
        </AuthProviders>
      </body>
    </html>
  );
}
